language: android
jdk:
  - oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-25
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    # The BuildTools version used by your project
    - tools
    - build-tools-25.0.2
    - platform-tools

    # The SDK version used to compile your project
    - $ANDROID_TARGET

    # Additional components
    - extra-google-google_play_services
    - extra-google-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
    - sys-img-${ANDROID_ABI}-android-19

# CodeCov script
script:
  - ./gradlew gradlew -PenableClover clean cloverHtmlReport
  - ./gradlew connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)
