language: android

jdk:
  - oraclejdk8

env:
  global:
    - ANDROID_TARGET_API=android-25
    - ANDROID_EMULATOR_API=android-21

android:
  components:
    # The BuildTools version used by your project
    - tools
    - build-tools-25.0.2
    - platform-tools

    # The SDK version used to compile your project
    - $ANDROID_TARGET_API

    # Additional components
    - extra-google-google_play_services
    - extra-google-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # System images to run emulator(s) during tests
    - sys-img-${ANDROID_ABI}-${ANDROID_EMULATOR_API}


before_script:
  - android list targets
  - echo no | android create avd --force --name test --target $ANDROID_EMULATOR_API --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

script:
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash
